#!/usr/bin/env python3

from src.registries import set_registry_value

# interfaces
set_registry_value(
    "control-interfaces",
    {
        "config.wlan0": {
            "interface-type": "wifi",
            "ip-address": "192.168.0.104",
        },
    },
)
set_registry_value(
    "control-interfaces",
    {"stats.wlan0": {"n-sent": 0, "n-received": 0}},
)

set_registry_value(
    "control-interfaces",
    {
        "config.eth0": {
            "interface-type": "ethernet",
            "ip-address": "172.16.0.3",
        }
    },
)
set_registry_value(
    "control-interfaces",
    {"stats.eth0": {"n-sent": 0, "n-received": 0}},
)

# tunnel
set_registry_value(
    "control-tunnel",
    {
        "interface": "eth0",
        "secret-key": "some-secret-key",
        "peers": ["192.168.21.3", "192.168.21.5", "192.168.21.7"],
    },
)

# telemetry
set_registry_value(
    "control-telemetry",
    {
        "sample-rate": 2,
        "monitor-packets-sent": True,
        "monitor-packets-received": False,
        "monitor-peers": True,
    },
)
