name: aspects-poc-control
base: core22
version: "0.1"
license: GPL-2.0-only
summary: Snap that pulls and applies aspects config.
description: |
  This snap syncs with the registration server to register
  devices and sync configuration.

grade: devel
confinement: devmode

environment:
  ACCOUNT_ID: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN

apps:
  daemon:
    command: bin/control-cli
    daemon: oneshot
    timer: 00:00-24:00/1440  # every minute

parts:
  control:
    plugin: python
    source: .
    parse-info:
      - setup.py
